name: Update README with Recent GitHub Activity

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Recent GitHub Activity - Profile README
        uses: Readme-Workflows/recent-activity@v2.3.2
        with:
          GH_USERNAME: FinnTheHero
          CONFIG_FILE: ./.github/recent-activity.config.yml
